import type { Upgrade } from '../../types';

export const BAUBLE_UPGRADES = [
  {
    id: 'bauble_glass_burr',
    name: 'Glass Burr',
    desc: '+5% damage to frozen enemies per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '....r.......',
      '...rQr......',
      '..rqQr......',
      '.rqDQr......',
      '..rQQr......',
      '...rQq......',
      '....r.......',
    ],
    bauble: { damageToFrozenMul: 0.05 },
  },
  {
    id: 'bauble_rime_coin',
    name: 'Rime Coin',
    desc: '+3% damage to slowed or chilled enemies per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '....qqq.....',
      '...qrrrq....',
      '..qroorq....',
      '..qrppq.....',
      '..qroorq....',
      '...qrrrq....',
      '....qqq.....',
    ],
    bauble: { damageToSlowedMul: 0.03 },
  },
  {
    id: 'bauble_snowmelt_pin',
    name: 'Snowmelt Pin',
    desc: '+3% freeze and lightning-stun duration per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '....d.......',
      '....cd......',
      '....cQd.....',
      '..qqcQq.....',
      '.qrrcqq.....',
      '....c.......',
      '....m.......',
      '.....m......',
    ],
    bauble: { freezeDurationMul: 0.03, stunDurationMul: 0.03 },
  },
  {
    id: 'bauble_icicle_lens',
    name: 'Icicle Lens',
    desc: '+1.5% crit chance against frozen enemies per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '...888......',
      '..8rrr8.....',
      '.8rQqr8.....',
      '.8rqqr8.....',
      '..8rr8......',
      '...88c......',
      '.....c......',
    ],
    bauble: { frozenCritChance: 0.015 },
  },
  {
    id: 'bauble_venom_thimble',
    name: 'Venom Thimble',
    desc: '+3% poison tick damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 12,
    icon: [
      '...llll.....',
      '..lzzzl.....',
      '..lzml......',
      '..lzzl......',
      '..llll......',
      '...mm.......',
      '....m.......',
    ],
    bauble: { poisonTickDamageMul: 0.03 },
  },
  {
    id: 'bauble_mold_button',
    name: 'Mold Button',
    desc: '+4% poison duration per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...llll.....',
      '..lmmmml....',
      '.lmklkml....',
      '.lmkklml....',
      '..lmmmml....',
      '...llll.....',
      '....z.......',
    ],
    bauble: { poisonDurationMul: 0.04 },
  },
  {
    id: 'bauble_toadstool_cap',
    name: 'Toadstool Cap',
    desc: '+5% damage to poisoned enemies per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '....hh......',
      '..hhjjhh....',
      '.hjjQjQh....',
      '.hhhhhhh....',
      '...666......',
      '..6zz6......',
      '..6..6......',
    ],
    bauble: { damageToPoisonedMul: 0.05 },
  },
  {
    id: 'bauble_viper_thread',
    name: 'Viper Thread',
    desc: '+3% poison application DPS per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '..mmmmm.....',
      '.mkkkzm.....',
      '.....zm.....',
      '...mmm......',
      '..mz........',
      '..mzzm......',
      '...mm.......',
    ],
    bauble: { poisonApplicationDpsMul: 0.03 },
  },
  {
    id: 'bauble_ember_bead',
    name: 'Ember Bead',
    desc: '+2% burn tick damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 12,
    icon: [
      '....tt......',
      '...tuuut....',
      '..tuOOvt....',
      '..tuuvvt....',
      '...tuuut....',
      '....tt......',
    ],
    bauble: { burnTickDamageMul: 0.02 },
  },
  {
    id: 'bauble_soot_button',
    name: 'Soot Button',
    desc: '+3% fire hit damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...0000.....',
      '..0tttu0....',
      '.0t0u0t0....',
      '.0tu0ut0....',
      '..0ttt0.....',
      '...000......',
    ],
    bauble: { fireDamageMul: 0.03 },
  },
  {
    id: 'bauble_cinder_locket',
    name: 'Cinder Locket',
    desc: '+4% damage to burning enemies per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '....88......',
      '...8ff8.....',
      '..8fOO8.....',
      '..8Ovv8.....',
      '..8fOO8.....',
      '...888......',
      '....8.......',
    ],
    bauble: { damageToBurningMul: 0.04 },
  },
  {
    id: 'bauble_coal_lens',
    name: 'Coal Lens',
    desc: '+1% crit chance for fire projectiles per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '...666......',
      '..60006.....',
      '.60uOu6.....',
      '.60Ovu6.....',
      '..6006......',
      '...66.......',
    ],
    bauble: { fireProjectileCritChance: 0.01 },
  },
  {
    id: 'bauble_tin_antenna',
    name: 'Tin Antenna',
    desc: '+3% lightning hit damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '.....D......',
      '....DqD.....',
      '.....c......',
      '.....c......',
      '....cbc.....',
      '...b...b....',
      '..b.....b...',
    ],
    bauble: { lightningDamageMul: 0.03 },
  },
  {
    id: 'bauble_copper_knot',
    name: 'Copper Knot',
    desc: '+3% chain damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...7777.....',
      '..7Oxx7.....',
      '.7x777x7....',
      '.7x7.7x7....',
      '..7xxx7.....',
      '...777......',
    ],
    bauble: { chainDamageMul: 0.03 },
  },
  {
    id: 'bauble_static_pebble',
    name: 'Static Pebble',
    desc: '+2% lightning chain range per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '...bbbb.....',
      '..bccccb....',
      '.bcqDcb.....',
      '.bccqDb.....',
      '..bcccb.....',
      '...bbb......',
    ],
    bauble: { chainRangeMul: 0.02 },
  },
  {
    id: 'bauble_moonlit_die_chip',
    name: 'Moonlit Die Chip',
    desc: '+3% arcane hit damage per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '...GGGG.....',
      '..GHHIG.....',
      '..GHQ.G.....',
      '..G..HG.....',
      '...GGG......',
      '....G.......',
    ],
    bauble: { arcaneDamageMul: 0.03 },
  },
  {
    id: 'bauble_bent_needle',
    name: 'Bent Needle',
    desc: '+3% projectile damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '.....d......',
      '....d.......',
      '...d........',
      '..d.........',
      '..cd........',
      '...cd.......',
      '....c.......',
    ],
    bauble: { projectileDamageMul: 0.03 },
  },
  {
    id: 'bauble_feather_fletching',
    name: 'Feather Fletching',
    desc: '+3% projectile speed per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '.....D......',
      '....DCC.....',
      '...DCCC.....',
      '..DCCCC.....',
      '...DCC......',
      '....D.......',
      '...6........',
    ],
    bauble: { projectileSpeedMul: 0.03 },
  },
  {
    id: 'bauble_cracked_marble',
    name: 'Cracked Marble',
    desc: '+2% projectile radius per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...cccc.....',
      '..cddddc....',
      '.cdQccd.....',
      '.cdcQdc.....',
      '..cdddc.....',
      '...cccc.....',
    ],
    bauble: { projectileRadiusMul: 0.02 },
  },
  {
    id: 'bauble_brass_lens',
    name: 'Brass Lens',
    desc: '+1% projectile crit chance per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '...888......',
      '..8vvv8.....',
      '.8vQQv8.....',
      '.8vQvv8.....',
      '..8vv8......',
      '...88.......',
    ],
    bauble: { projectileCritChance: 0.01 },
  },
  {
    id: 'bauble_spare_spring',
    name: 'Spare Spring',
    desc: '+3% projectile lifetime per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '..7777......',
      '.7....7.....',
      '...777......',
      '..7...7.....',
      '...777......',
      '......7.....',
      '..7777......',
    ],
    bauble: { projectileLifetimeMul: 0.03 },
  },
  {
    id: 'bauble_bell_shard',
    name: 'Bell Shard',
    desc: '+3% pulse damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...999......',
      '..98x8......',
      '.98x8.......',
      '.988........',
      '..98........',
      '...9..x.....',
    ],
    bauble: { pulseDamageMul: 0.03 },
  },
  {
    id: 'bauble_glass_prism',
    name: 'Glass Prism',
    desc: '+3% beam damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '.....D......',
      '....DHD.....',
      '...DCCHD....',
      '..DCCCCD....',
      '.DDDDDDD....',
      '....w..q....',
    ],
    bauble: { beamDamageMul: 0.03 },
  },
  {
    id: 'bauble_rusty_spur',
    name: 'Rusty Spur',
    desc: '+3% orbit damage per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '....6.......',
      '..6.7.6.....',
      '...777......',
      '.677O776....',
      '...777......',
      '..6.7.6.....',
      '....6.......',
    ],
    bauble: { orbitDamageMul: 0.03 },
  },
  {
    id: 'bauble_tiny_anvil',
    name: 'Tiny Anvil',
    desc: '+3% strike damage per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '..dddddd....',
      '..caaaa.....',
      '...aaa......',
      '..aaaaa.....',
      '.aaaaaaa....',
      '..a...a.....',
    ],
    bauble: { strikeDamageMul: 0.03 },
  },
  {
    id: 'bauble_lucky_splinter',
    name: 'Lucky Splinter',
    desc: '+3% damage from face values 1-2 per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...666......',
      '....66......',
      '...6Q6......',
      '..66........',
      '.66Q........',
      '..6.........',
    ],
    bauble: { lowFaceDamageMul: 0.03 },
  },
  {
    id: 'bauble_sixpence_nail',
    name: 'Sixpence Nail',
    desc: '+2% damage from face values 5-6 per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '..9999......',
      '.9Q9Q9......',
      '..999.......',
      '...c........',
      '...c........',
      '...c........',
      '...a........',
    ],
    bauble: { highFaceDamageMul: 0.02 },
  },
  {
    id: 'bauble_blooddrop_bead',
    name: 'Blooddrop Bead',
    desc: '+3% damage while below 50% HP per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '....h.......',
      '...hih......',
      '..hiih......',
      '..hiii......',
      '...hih......',
      '....h.......',
      '..00000.....',
    ],
    bauble: { lowHpDamageMul: 0.03 },
  },
  {
    id: 'bauble_salted_fang',
    name: 'Salted Fang',
    desc: '+3% damage to elites and bosses per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 8,
    icon: [
      '..Q.........',
      '..QQ........',
      '..QeQ.......',
      '..QeeQ......',
      '...QeeQ.....',
      '....QQ......',
      '...d..d.....',
    ],
    bauble: { damageToEliteBossMul: 0.03 },
  },
  {
    id: 'bauble_threadbare_bandage',
    name: 'Threadbare Bandage',
    desc: '+2% healing received per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '..666666....',
      '.6eeehe6....',
      '.6eehee6....',
      '.6eheee6....',
      '..666666....',
    ],
    bauble: { healingReceivedMul: 0.02 },
  },
  {
    id: 'bauble_safety_pin',
    name: 'Safety Pin',
    desc: 'Start each wave with +1 shield per stack, respecting shield cap.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 5,
    icon: [
      '..cccc......',
      '.c....c.....',
      'c......c....',
      'c..DD..c....',
      '.cccccc.....',
      '...bb.......',
    ],
    bauble: { waveStartShield: 1 },
  },
  {
    id: 'bauble_gilded_crumb',
    name: 'Gilded Crumb',
    desc: '+1% gold gain per stack.',
    rarity: 'common',
    category: 'bauble',
    maxStack: 10,
    icon: [
      '...x........',
      '..x9x.......',
      '...99.......',
      '.x999x......',
      '..999.......',
      '...x........',
    ],
    bauble: { goldGainMul: 0.01 },
  },
  {
    id: 'bauble_clockwork_seed',
    name: 'Clockwork Seed',
    desc: '-1.5% post-roll cooldown per stack.',
    rarity: 'rare',
    category: 'bauble',
    maxStack: 6,
    icon: [
      '...777......',
      '..7x7x7.....',
      '.77xO77.....',
      '..7x7x7.....',
      '...777......',
      '....m.......',
      '...m.m......',
    ],
    bauble: { cooldownReductionMul: 0.015 },
  },
  {
    id: 'bauble_whetstone_chip',
    name: 'Whetstone Chip',
    desc: '+1% all damage per stack.',
    rarity: 'epic',
    category: 'bauble',
    maxStack: 5,
    icon: [
      '..aaaa......',
      '.acccc......',
      '.acddcS.....',
      '..accc......',
      '...aa.......',
    ],
    bauble: { allDamageMul: 0.01 },
  },
] satisfies Upgrade[];
