import type { EnemyType } from '../../types';
import * as B from './behaviors';
import { palHex } from '../../sprites/palette';

export const ENEMY_TYPES: EnemyType[] = [
  {
    id: 'rusher',
    name: 'Debt Hound',
    spriteId: 'house_debt_hound',
    color: palHex('h')!,
    family: 'debt',
    role: 'Fast collector',
    lore: 'The House sends these low hounds after every unpaid roll.',
    tell: 'Crouches and flashes coin-bright eyes before the charge.',
    threat: 'Rushes lanes before slow faces can recover.',
    weakness: 'Falls quickly to early burst or any reliable multishot.',
    spawnLine: 'The debt hounds smell a loose coin.',
    deathLine: 'The collar snaps. The debt remains.',
    baseHp: 16,
    baseSpeed: 18,
    radius: 7,
    minWave: 1,
    weight: (w) => Math.max(2, 10 - w * 0.1),
    touchDamage: 8,
    scoreValue: 10,
    behavior: B.rusherBehavior,
  },
  {
    id: 'tank',
    name: 'Vaultback',
    spriteId: 'house_vaultback',
    color: palHex('6')!,
    family: 'vault',
    role: 'Armored blocker',
    lore: 'A walking strongbox with a monster folded inside the lock.',
    tell: 'Its safe-door shell rocks side to side under heavy weight.',
    threat: 'Soaks volleys while smaller servants cross behind it.',
    weakness: 'Pierce, beams, and focused high rolls crack the vault.',
    spawnLine: 'A vault door drags itself into the lane.',
    deathLine: 'The strongbox coughs out its last oath.',
    baseHp: 72,
    baseSpeed: 7,
    radius: 8,
    minWave: 2,
    weight: (w) => Math.min(4, 1 + w * 0.08),
    touchDamage: 14,
    scoreValue: 18,
    behavior: B.tankBehavior,
  },
  {
    id: 'splitter',
    name: 'Loaded Larva',
    spriteId: 'house_loaded_larva',
    color: palHex('p')!,
    family: 'brood',
    role: 'Brood carrier',
    lore: 'A crooked die egg, heavy with smaller bad outcomes.',
    tell: 'The shell bulges with twitching pips.',
    threat: 'Splits into quick pip-rats unless cleaned up safely.',
    weakness: 'Area damage and lingering zones erase the hatchlings.',
    spawnLine: 'Something loaded begins to hatch.',
    deathLine: 'The shell breaks into worse luck.',
    baseHp: 28,
    baseSpeed: 12,
    radius: 7,
    minWave: 3,
    weight: (w) => Math.min(4, 0.5 + w * 0.1),
    touchDamage: 10,
    scoreValue: 16,
    behavior: B.splitterBehavior,
    onDeath: (e) => {
      if ((e.data['split'] as number | undefined) === 1) return;
      setTimeout(() => {
        import('../../engine/engine').then(({ getEngineState }) => {
          const state = getEngineState();
          for (let i = 0; i < 2; i++) {
            const child = state.enemies.find((x) => !x.alive);
            if (!child) return;
            Object.assign(child, {
              alive: true,
              typeId: 'swarm',
              x: e.x + (i === 0 ? -8 : 8),
              y: e.y,
              vx: (i === 0 ? -12 : 12),
              vy: e.speed,
              maxHp: 14,
              hp: 14,
              radius: 5,
              speed: e.speed * 1.15,
              age: 0,
              state: 'walk' as const,
              flashT: 0,
              dieT: 0,
              data: { split: 1 },
              element: 'none' as const,
              hitFlash: 0,
              slow: 0,
              freeze: 0,
              poisonT: 0,
              poisonDps: 0,
              absorbed: 0,
            });
          }
        });
      }, 0);
    },
  },
  {
    id: 'swarm',
    name: 'Pip-Rat',
    spriteId: 'house_pip_rat',
    color: palHex('O')!,
    family: 'brood',
    role: 'Small flooder',
    lore: 'Loose pips gnawed free from dice that rolled badly.',
    tell: 'Skips in frantic zigzags as its single pip flickers.',
    threat: 'Overwhelms single-target builds in numbers.',
    weakness: 'Pulses, novas, and splash effects clear the pack.',
    spawnLine: 'Pips scatter under the table.',
    deathLine: 'One less pip in the swarm.',
    baseHp: 9,
    baseSpeed: 24,
    radius: 5,
    minWave: 2,
    weight: (w) => Math.min(6, 1 + w * 0.15),
    touchDamage: 5,
    scoreValue: 6,
    behavior: B.swarmBehavior,
  },
  {
    id: 'drifter',
    name: 'Chandelier Wisp',
    spriteId: 'house_chandelier_wisp',
    color: palHex('w')!,
    family: 'court',
    role: 'Evasive floater',
    lore: 'A ballroom light with a tiny hungry ghost in the glass.',
    tell: 'Sways as if tugged by invisible music.',
    threat: 'Dodges straight fire and makes aimless volleys whiff.',
    weakness: 'Homing, chain, and wide spreads catch the drift.',
    spawnLine: 'The ballroom lights begin to descend.',
    deathLine: 'The last candle gutters out.',
    baseHp: 24,
    baseSpeed: 13,
    radius: 6,
    minWave: 4,
    weight: (w) => Math.min(5, 0.5 + w * 0.12),
    touchDamage: 9,
    scoreValue: 14,
    behavior: B.drifterBehavior,
  },
  {
    id: 'oddonly',
    name: 'Odd Apostle',
    spriteId: 'house_odd_apostle',
    color: palHex('G')!,
    family: 'court',
    role: 'Pip-gated zealot',
    lore: 'A robed servant preaching that even numbers are heresy.',
    tell: 'Only the odd pips on its mask glow.',
    threat: 'Ignores even rolls and punishes unfocused dice tables.',
    weakness: 'Odd faces, face-value control, and multi-dice consistency.',
    spawnLine: 'The odd apostle counts your sins in threes.',
    deathLine: 'Its sermon ends on an odd note.',
    baseHp: 34,
    baseSpeed: 10,
    radius: 7,
    minWave: 6,
    weight: (w) => Math.min(3, 0.4 + (w - 6) * 0.08),
    touchDamage: 11,
    scoreValue: 22,
    behavior: B.oddOnlyBehavior,
    damageFilter: (roll) => roll.face.value % 2 === 1,
  },
  {
    id: 'copier',
    name: 'Mirror Clerk',
    spriteId: 'house_mirror_clerk',
    color: palHex('P')!,
    family: 'mirror',
    role: 'Pattern reader',
    lore: 'A clerk behind mirrored glass, filing copies of your best rolls.',
    tell: 'Its face flips between blank parchment and your last shot.',
    threat: 'Slips sideways while the lane fills around it.',
    weakness: 'Burst windows and non-projectile damage deny its paperwork.',
    spawnLine: 'A clerk opens a ledger with your name in it.',
    deathLine: 'The duplicate entry burns away.',
    baseHp: 32,
    baseSpeed: 12,
    radius: 6,
    minWave: 7,
    weight: (w) => Math.min(3, 0.3 + (w - 7) * 0.08),
    touchDamage: 10,
    scoreValue: 20,
    behavior: B.copierBehavior,
  },
  {
    id: 'debuffer',
    name: 'Tithe Drainer',
    spriteId: 'house_tithe_drainer',
    color: palHex('U')!,
    family: 'debt',
    role: 'Tempo taxer',
    lore: 'A collector that invoices time instead of gold.',
    tell: 'A blue receipt-thread trails from its claws.',
    threat: 'Lingers near the wall and makes every mistake feel slower.',
    weakness: 'Priority fire before it reaches its tax window.',
    spawnLine: 'The House posts a late fee.',
    deathLine: 'The receipt tears in half.',
    baseHp: 36,
    baseSpeed: 9,
    radius: 7,
    minWave: 8,
    weight: (w) => Math.min(2, 0.2 + (w - 8) * 0.06),
    touchDamage: 8,
    scoreValue: 24,
    behavior: B.debufferBehavior,
  },
  {
    id: 'absorber',
    name: 'Null Maw',
    spriteId: 'house_null_maw',
    color: palHex('B')!,
    family: 'null',
    role: 'Projectile eater',
    lore: 'A hungry pocket of table-felt where good shots disappear.',
    tell: 'Its hollow center brightens as it drinks damage.',
    threat: 'Feeds on projectiles and speeds up when overstuffed.',
    weakness: 'Pulses, beams, poison, and patient burst timing.',
    spawnLine: 'A black mouth opens in the table.',
    deathLine: 'The void finally swallows itself.',
    baseHp: 42,
    baseSpeed: 8,
    radius: 7,
    minWave: 9,
    weight: (w) => Math.min(2, 0.2 + (w - 9) * 0.05),
    touchDamage: 12,
    scoreValue: 28,
    behavior: B.absorberBehavior,
  },
  {
    id: 'healer',
    name: 'House Surgeon',
    spriteId: 'house_surgeon',
    color: palHex('m')!,
    family: 'suture',
    role: 'Support medic',
    lore: 'The House keeps a needle for monsters that should have died.',
    tell: 'Red stitches pulse from its hands to nearby servants.',
    threat: 'Restores wounded enemies and extends bad formations.',
    weakness: 'Kill first; splash around it denies the operating room.',
    spawnLine: 'A surgeon wheels in fresh thread.',
    deathLine: 'The needle drops. The patient screams.',
    baseHp: 30,
    baseSpeed: 9,
    radius: 7,
    minWave: 10,
    weight: (w) => Math.min(2, 0.2 + (w - 10) * 0.04),
    touchDamage: 8,
    scoreValue: 30,
    behavior: B.healerBehavior,
    bossMechanic: (e, dt) => {
      e.data['pulseT'] = ((e.data['pulseT'] as number | undefined) ?? 0) + dt;
      if ((e.data['pulseT'] as number) > 2) {
        e.data['pulseT'] = 0;
        import('../../engine/engine').then(({ getEngineState }) => {
          const state = getEngineState();
          for (const o of state.enemies) {
            if (!o.alive || o === e || o.state === 'die') continue;
            const dx = o.x - e.x;
            const dy = o.y - e.y;
            if (dx * dx + dy * dy < 40 * 40) {
              o.hp = Math.min(o.maxHp, o.hp + o.maxHp * 0.15);
            }
          }
        });
      }
    },
  },
  {
    id: 'invisible',
    name: 'Curtain Shade',
    spriteId: 'house_curtain_shade',
    color: palHex('w')!,
    family: 'grave',
    role: 'Hidden ambusher',
    lore: 'A dead patron hiding in velvet folds between rooms.',
    tell: 'Only a pale hem shows until it nears the wall.',
    threat: 'Crosses distance while barely visible.',
    weakness: 'Persistent fields, wide pulses, and tracking effects.',
    spawnLine: 'The curtains breathe.',
    deathLine: 'The velvet falls empty.',
    baseHp: 22,
    baseSpeed: 14,
    radius: 6,
    minWave: 11,
    weight: (w) => Math.min(3, 0.3 + (w - 11) * 0.05),
    touchDamage: 10,
    scoreValue: 26,
    behavior: B.invisibleBehavior,
  },
  {
    id: 'inverter',
    name: 'Flip Jester',
    spriteId: 'house_flip_jester',
    color: palHex('F')!,
    family: 'court',
    role: 'Value trickster',
    lore: 'A capering fool who insists every die is upside down.',
    tell: 'Its mask rotates whenever your roll lands.',
    threat: 'Pressures builds that rely on a narrow face band.',
    weakness: 'Flexible dice tables and damage that does not care about pips.',
    spawnLine: 'The jester bows from the wrong side of the floor.',
    deathLine: 'The joke lands face down.',
    baseHp: 38,
    baseSpeed: 10,
    radius: 7,
    minWave: 14,
    weight: (w) => Math.min(2, 0.2 + (w - 14) * 0.05),
    touchDamage: 11,
    scoreValue: 32,
    behavior: B.inverterBehavior,
    onHit: () => {},
  },
  {
    id: 'reflector',
    name: 'Mirror Bailiff',
    spriteId: 'house_mirror_bailiff',
    color: palHex('C')!,
    family: 'mirror',
    role: 'Reflective guard',
    lore: 'A bailiff in polished armor, sworn to return every accusation.',
    tell: 'Its shield flashes with a hard white glint.',
    threat: 'Punishes careless projectile spam and stalls lanes.',
    weakness: 'Pulses, beams, and timing shots between mirror flashes.',
    spawnLine: 'A bailiff raises the mirrored writ.',
    deathLine: 'The warrant cracks down the middle.',
    baseHp: 36,
    baseSpeed: 8,
    radius: 7,
    minWave: 15,
    weight: (w) => Math.min(2, 0.15 + (w - 15) * 0.04),
    touchDamage: 12,
    scoreValue: 34,
    behavior: B.reflectorBehavior,
  },
  {
    id: 'resurrector',
    name: 'Grave Usher',
    spriteId: 'house_grave_usher',
    color: palHex('V')!,
    family: 'grave',
    role: 'Death cheater',
    lore: 'An usher who shows dead servants back to their seats.',
    tell: 'A burial bell swings in its ribcage.',
    threat: 'Turns clean kills into second waves of pressure.',
    weakness: 'Burst it with enough follow-up to kill the return body.',
    spawnLine: 'The grave usher takes attendance.',
    deathLine: 'No encore this time.',
    baseHp: 42,
    baseSpeed: 9,
    radius: 7,
    minWave: 16,
    weight: (w) => Math.min(2, 0.15 + (w - 16) * 0.04),
    touchDamage: 12,
    scoreValue: 36,
    behavior: B.resurrectorBehavior,
    onDeath: (e) => {
      if ((e.data['revived'] as number | undefined) === 1) return;
      setTimeout(() => {
        import('../../engine/engine').then(({ getEngineState }) => {
          const state = getEngineState();
          const child = state.enemies.find((x) => !x.alive);
          if (!child) return;
          Object.assign(child, {
            alive: true,
            typeId: 'rusher',
            x: e.x,
            y: e.y,
            vx: 0,
            vy: e.speed,
            maxHp: 22,
            hp: 22,
            radius: 6,
            speed: e.speed * 1.3,
            age: 0,
            state: 'walk' as const,
            flashT: 0,
            dieT: 0,
            data: { revived: 1 },
            element: 'none' as const,
            hitFlash: 0,
            slow: 0,
            freeze: 0,
            poisonT: 0,
            poisonDps: 0,
            absorbed: 0,
          });
        });
      }, 0);
    },
  },
  {
    id: 'immune',
    name: 'Six-Seal Guard',
    spriteId: 'house_six_seal_guard',
    color: palHex('A')!,
    family: 'vault',
    role: 'Sealed defender',
    lore: 'A guard whose armor only opens for respectable rolls.',
    tell: 'Three sealed pips stay dark across its breastplate.',
    threat: 'Invalidates low-value chip damage.',
    weakness: 'Faces 3-6, upgraded high rolls, and heavy single hits.',
    spawnLine: 'The six-seal guard checks your roll at the door.',
    deathLine: 'The seal fails with a heavy click.',
    baseHp: 48,
    baseSpeed: 6,
    radius: 7,
    minWave: 18,
    weight: (w) => Math.min(2, 0.15 + (w - 18) * 0.04),
    touchDamage: 14,
    scoreValue: 42,
    behavior: B.immuneBehavior,
    damageFilter: (roll) => roll.face.value >= 3,
  },
];
