import { defineSprite } from './sprite';

const faceLockerA = [
  '......3333333333......',
  '.....3FFFFFFFFFF3.....',
  '....3FGGGGGGGGGGF3....',
  '...3FGHHHHHHHHHHGF3...',
  '..3FGHIIIIIIIIIIHGF3..',
  '.3FGHIIIwwwwwIIIHGF3..',
  '3FGHIIww111wwIIIIHGF3.',
  '3FGHIIw1I1I1wwIIIHGF3.',
  '3FGHIIw11I11wIIIIHGF3.',
  '3FGHIIww111wwIIIIHGF3.',
  '3FGHIIIwwwwwIIIIIHGF3.',
  '3FGHIIIIIIIIIIIIIHGF3.',
  '3FGHHxxIIIIIIIIxxHGF3.',
  '3FGHHIxxIIIIIIxxHHGF3.',
  '3FGGHHHxIIIIIxHHHGGF3.',
  '.3FGGHHHHHHHHHHHGGF3..',
  '..3FGGGGGGGGGGGGGF3...',
  '...3FFFGGGGGGGGFF3....',
  '....33FF3333FFFF3.....',
  '.....3FF3.3FFF3.......',
  '......33.3.333........',
  '......................',
];

const faceLockerB = [
  '......3333333333......',
  '.....3FFFFFFFFFF3.....',
  '....3FGGGGGGGGGGF3....',
  '...3FGHHHHHHHHHHGF3...',
  '..3FGHIIIIIIIIIIHGF3..',
  '.3FGHIIIwwwwwIIIHGF3..',
  '3FGHIIwww1wwIIIIHGF3.',
  '3FGHIIwI1I1I1wIIIHGF3',
  '3FGHIIw11I11wIIIIHGF3',
  '3FGHIIww111wwIIIIHGF3',
  '3FGHIIIwwwwwIIIIIHGF3',
  '3FGHIIIIIIIIIIIIIHGF3',
  '3FGHIIxxIIIIIIxxIHGF3',
  '3FGHHxxIIIIIIIIxxHGF3',
  '3FGGHHHxIIIIIxHHHGGF3',
  '.3FGGHHHHHHHHHHHGGF3.',
  '..3FGGGGGGGGGGGGGF3..',
  '...3FFFGGGGGGGGFF3...',
  '....3FF3333FFFF33....',
  '.....33.3FFF3.3......',
  '.....3...333.........',
  '.....................',
];

const splitterQueenA = [
  '.......1111111.......',
  '......1opppppo1......',
  '.....1oppyyyppo1.....',
  '....1oppyy11yypo1....',
  '...1oppyy11y11ypo1...',
  '...1opyy11I11yypo1...',
  '..1oppyyIIIIIyyypo1..',
  '..1oppyyIII22Iyypo1..',
  '..1opyyIIII22IIyyo1..',
  '..1oppyyIIIIIIIyyo1..',
  '..1opppyyyyyyyyypo1..',
  '..1oppppyyoyyyppo1...',
  '..1oooppppoppppoo1...',
  '...1oooopoooooo1.....',
  '....1oooooooo1.......',
  '....1o.1o..1o1.......',
  '....o...1...o........',
  '...1....1....1.......',
  '...o....1....o.......',
  '..1o....1....o1......',
  '.....................',
  '.....................',
];

const splitterQueenB = [
  '.......1111111.......',
  '......1opppppo1......',
  '.....1oppyyyppo1.....',
  '....1oppyy11yypo1....',
  '...1opyy11y11yypo1...',
  '...1opyyy1I1yyypo1...',
  '..1opppyIIIIIyyppo1..',
  '..1oppyy22III22yyo1..',
  '..1opyyIII22IIIyyo1..',
  '..1oppyyyIIIIIIyyo1..',
  '..1opppyyyyyyyyypo1..',
  '..1ooppoyyyoppppoo1..',
  '..1oppppoooooopppo1..',
  '...1oooopoooooo1.....',
  '....1oooooooo1.......',
  '...1o.1.o.o.1o1......',
  '....o..1.1..o........',
  '...o..1...1..o.......',
  '..1o....1....o1......',
  '.1o.....1.....o1.....',
  '.....................',
  '.....................',
];

const mirrorTwinA = [
  '......2222222222......',
  '.....2HHHHHHHHH2......',
  '....2HIIIIIIIII2......',
  '....2HIcccccII2.......',
  '....2HIcdddcII2.......',
  '....2HIcdRdcII2.......',
  '....2HIcddd22......... ',
  '....2HIcddddII2.......',
  '....2HIccddcII2.......',
  '....2HIIIcIIII2.......',
  '.....2HHHHHHHH2.......',
  '......2HHHHHH2........',
  '.....wHHHHHHHHw.......',
  '....wHHwwwwwwwHHw.....',
  '...wHHwwHHHHwwwHHw....',
  '...wwHHHHHHHHHHHww....',
  '....wHHwwwwwHHHw......',
  '.....wwHHHwwww........',
  '......22....22........',
  '......55....55........',
  '......66....66........',
  '......................',
];

const mirrorTwinB = [
  '......2222222222......',
  '.....2HHHHHHHHH2......',
  '....2HIIIIIIIII2......',
  '....2HIcccccII2.......',
  '....2HIcdddcII2.......',
  '....2HIcdRdcII2.......',
  '....2HIcddd22.........',
  '....2HIcddddII2.......',
  '....2HIccddcII2.......',
  '....2HIIIcIIII2.......',
  '.....2HHHHHHHH2.......',
  '......2HHHHHH2........',
  '....wHHHHHHHHHHw......',
  '..wHHHHwwwwwwHHHHw....',
  '..wHHwwHHHHHHwwHHw....',
  '...wwHHHHHHHHHHHww....',
  '....wHHwwHHwwwHHHw....',
  '.....wwHwwwwHHww......',
  '......22....22........',
  '......55....55........',
  '......66....66........',
  '......................',
];

const nullZoneA = [
  '......3333333333......',
  '.....3EEEEEEEEEE3.....',
  '....3EFFFFFFFFFFE3....',
  '...3EFGGGGGGGGGGF3....',
  '..3EFGwwwwwwwwwwGF3...',
  '.3EFGwHHHHHHHHHHwGF3..',
  '3EFGwHIIIIIIIIIIHwGF3.',
  '3EFGwHIRRRRRRRRIHwGF3.',
  '3EFGwHIRSSSSRRIIHwGF3.',
  '3EFGwHIRSRRSSRIIHwGF3.',
  '3EFGwHIRRSSRRRIIHwGF3.',
  '3EFGwHIRSSSRRRIIHwGF3.',
  '3EFGwHIIRRRRIIIHwwGF3.',
  '3EFGwHHIIIIIIIHHwwGF3.',
  '3EFGwwHHHHHHHHwwwwGF3.',
  '.3EFGGwwwwwwwwwGGGF3..',
  '..3EFGGGGGGGGGGGGGF3..',
  '...3EEFFFFFFFFFFFF3...',
  '....3EEEEEEEEEE3......',
  '.....333333333........',
  '......................',
  '......................',
];

const nullZoneB = [
  '......3333333333......',
  '.....3EEEEEEEEEE3.....',
  '....3EFFFFFFFFFFE3....',
  '...3EFGGGGGGGGGGF3....',
  '..3EFGwwwwwwwwwwGF3...',
  '.3EFGwHHHHHHHHHHwGF3..',
  '3EFGwHIIIIIIIIIIHwGF3',
  '3EFGwHIRRRSSRRRIHwGF3',
  '3EFGwHIRSRRSSRRIHwGF3',
  '3EFGwHIRRSSSRRRIHwGF3',
  '3EFGwHIRSSRRSSRIHwGF3',
  '3EFGwHIRRRRSSSRIHwGF3',
  '3EFGwHIISSRRRIIIHwGF3',
  '3EFGwHHIIIIIIIIIwwGF3',
  '3EFGwwHHHHHHHHwwwwGF3',
  '.3EFGGwwwwwwwwwGGGF3.',
  '..3EFGGGGGGGGGGGGGF3.',
  '...3EEFFFFFFFFFFFF3..',
  '....3EEEEEEEEEEE3....',
  '.....33333333333.....',
  '.....................',
  '.....................',
];

const invertKingA = [
  '......5555555555......',
  '.....5MMMMMMMMMMM5....',
  '....5MNNNNNNNNNNNM5...',
  '...5MNOOOOOOOOOOON5...',
  '..5MNOvvvvvvvvvvvON5..',
  '..5MNOvxxxxxxxxxvON5.',
  '.5MNOvxvvvvvvvvxvON5.',
  '.5MNOvxvuuvvuuvxvON5.',
  '.5MNOvxvuRuvuRuvxON5.',
  '.5MNOvxvuuvvuuvxvON5.',
  '.5MNOvxvvvvvvvvxvON5.',
  '.5MNOvxvvvvuvvvxvON5.',
  '.5MNOvxvvsssssvxvON5.',
  '.5MNOvxxvssssvxxvON5.',
  '.5MNOvvxxvvvvxxvvON5.',
  '..5MNOvvvxxxxvvvON5..',
  '..5MNNOOOvvvvOOONN5..',
  '...5MMNNNOOOONNNM5...',
  '....5MMMNNNNNNNM5....',
  '.....55MMMMMM55......',
  '.......55555.........',
  '.....................',
];

const invertKingB = [
  '......5555555555......',
  '.....5MMMMMMMMMMM5....',
  '....5MNNNNNNNNNNNM5...',
  '...5MNOOOOOOOOOOON5...',
  '..5MNOvvvvvvvvvvvON5..',
  '..5MNOvxxxxxxxxxvON5.',
  '.5MNOvxvvvvvvvvxvON5.',
  '.5MNOvxuuvvvvuuxvON5.',
  '.5MNOvxuRuvvuRuxvON5.',
  '.5MNOvxuuvvvvuuxvON5.',
  '.5MNOvxvvvvuvvvxvON5.',
  '.5MNOvxvvvuuvvvxvON5.',
  '.5MNOvxvssssssvxvON5.',
  '.5MNOvxxsssssvxxvON5.',
  '.5MNOvvxxvvvvxxvvON5.',
  '..5MNOvvvxxxxvvvON5..',
  '..5MNNOOOvvvvOOONN5..',
  '...5MMNNNOOOONNNM5...',
  '....5MMMNNNNNNNM5....',
  '.....55MMMMMM55......',
  '.......55555.........',
  '.....................',
];

const reflectorBossA = [
  '......qqqqqqqqqq......',
  '.....qrrrrrrrrrrq.....',
  '....qrDDDDDDDDDDrq....',
  '...qrDCCCCCCCCCCDrq...',
  '..qrDCBBBBBBBBBBCDrq..',
  '.qrDCBAAAAAAAAAABCDrq.',
  'qrDCBARRRRRRRRRRABCDrq',
  'qrDCBARSSSSSSSSRABCDrq',
  'qrDCBARSCCCCCCSRABCDrq',
  'qrDCBARSCRRRRCSRABCDrq',
  'qrDCBARSCRSSRCSRABCDrq',
  'qrDCBARSCRSSRCSRABCDrq',
  'qrDCBARSCRRRRCSRABCDrq',
  'qrDCBARSCCCCCCSRABCDrq',
  'qrDCBARSSSSSSSSRABCDrq',
  'qrDCBARRRRRRRRRRABCDrq',
  '.qrDCBBAAAAAAAABBCDrq.',
  '..qrDCCBBBBBBBBCCDrq..',
  '...qrDDCCCCCCCCDrq....',
  '....qrrDDDDDDDDrrq....',
  '.....qqrrrrrrrrqq.....',
  '.......qqqqqqqq.......',
];

const reflectorBossB = [
  '......qqqqqqqqqq......',
  '.....qrrrrrrrrrrq.....',
  '....qrDDDDDDDDDDrq....',
  '...qrDCCCCCCCCCCDrq...',
  '..qrDCBBBBBBBBBBCDrq..',
  '.qrDCBAAAAAAAAAABCDrq.',
  'qrDCBARRRRRRRRRRABCDrq',
  'qrDCBARSSCCCCSSRABCDrq',
  'qrDCBARSCRRRRCSRABCDrq',
  'qrDCBARSCRSSRCSRABCDrq',
  'qrDCBARSCRSRRCSRABCDrq',
  'qrDCBARSCRRSRCSRABCDrq',
  'qrDCBARSCRSSRCSRABCDrq',
  'qrDCBARSCRRRRCSRABCDrq',
  'qrDCBARSSCCCCSSRABCDrq',
  'qrDCBARRRRRRRRRRABCDrq',
  '.qrDCBBAAAAAAAABBCDrq.',
  '..qrDCCBBBBBBBBCCDrq..',
  '...qrDDCCCCCCCCDrq....',
  '....qrrDDDDDDDDrrq....',
  '.....qqrrrrrrrrqq.....',
  '.......qqqqqqqq.......',
];

const bossDie = [
  '......................',
  '......................',
  '.......1111111........',
  '......1aaaaaa1........',
  '.....1aPPPPaa1........',
  '....1aPPaaPPaa1.......',
  '....1aaPPaaPPa1.......',
  '....1aPaaaPPaa1.......',
  '.....1aaaaaa1.........',
  '......1aaaa1..........',
  '.......1111...........',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];

function defBoss(id: string, a: string[], b: string[]): void {
  defineSprite({
    id,
    frames: [a, b, bossDie],
    anchor: 'center',
    anim: {
      walk: { name: 'walk', frames: [0, 1], frameDuration: 0.35, loop: true },
      die: { name: 'die', frames: [2], frameDuration: 0.3, loop: false },
    },
  });
}

export function defineBossSprites(): void {
  defBoss('boss_facelocker', faceLockerA, faceLockerB);
  defBoss('boss_splitterqueen', splitterQueenA, splitterQueenB);
  defBoss('boss_mirrortwin', mirrorTwinA, mirrorTwinB);
  defBoss('boss_nullzone', nullZoneA, nullZoneB);
  defBoss('boss_invertking', invertKingA, invertKingB);
  defBoss('boss_reflector', reflectorBossA, reflectorBossB);
}
