import { defineSprite } from './sprite';

const soldierIdleA = [
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
  '...5666...6665..',
];

const soldierIdleB = [
  '................',
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierHit = [
  '................',
  '.....LLLLLLL....',
  '....LiiiiiiiL...',
  '...LijjjjjjjiL..',
  '..LijjjjjjjjiL..',
  '..Lij11jjj11jiL.',
  '..LijjjjjjjjiL..',
  '..Lijjjj2jjjiL..',
  '..LiijjjjjjjiL..',
  '...LijjjjjjjiL..',
  '...LLLiiiiiLLL..',
  '..LLLLLLLLLLLL..',
  '.LLLLLLLLLLLLLL.',
  '.LLLLLLLLLLLLLL.',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '....LLL...LLL...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierDeath = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '......aaaaa.....',
  '....abbbbbba....',
  '...abcccccbba...',
  '..abcddc11cba...',
  '..abcddddcba....',
  '..abbcdddcba....',
  '...abbbbba......',
  '.aahhhhhhhhaa...',
  'ahhhxvhhhvxhhaa.',
  'ahhvxvvvvxvhha..',
  'aahhhhhhhhhhaa..',
  '..aaaaaaaaaaa...',
  '...5555555555...',
  '....555555555...',
  '....666666666...',
  '................',
  '................',
];

const gamblerIdleA = [
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerIdleB = [
  '................',
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerHit = gamblerIdleA.map(replaceToHit);
const gamblerDeath = [
  '................',
  '................',
  '................',
  '.....222222.....',
  '....22222222....',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcdddcba....',
  '....abcccba.....',
  '..4444444444....',
  '.44443aaaa3444..',
  '.444aaaaaaa444..',
  '..4444444444....',
  '...444aaa444....',
  '...44......44...',
  '...2........2...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

const alchemistIdleA = [
  '......FFFF......',
  '.....FGGGGF.....',
  '....FGHHHHGF....',
  '...FGHFFFFHGF...',
  '...FHFzzFFHGF...',
  '...FHFRRRRHGF...',
  '...FGHFRFHGGF...',
  '....FGHHHGGF....',
  '...TTTUUUTTT....',
  '..TUUUDDDUUUT...',
  '.TUUDDzzDDUUT...',
  '.TUUDDmmDDUUT...',
  '.TUUUDDDDUUUT...',
  '..TTUCCCCUTT....',
  '...TUCzzCUT.....',
  '...TUCDDCUT.....',
  '..PTUUUUUUTP....',
  '..QP.....PQ.....',
  '....55...55.....',
  '....55...55.....',
  '...666...666....',
  '...555...555....',
];

const alchemistIdleB = [
  '................',
  '......FFFF......',
  '.....FGGGGF.....',
  '....FGHHHHGF....',
  '...FGHFFFFHGF...',
  '...FHFzzFFHGF...',
  '...FHFRRRRHGF...',
  '...FGHFRFHGGF...',
  '....FGHHHGGF....',
  '...TTTUUUTTT....',
  '..TUUUDDDUUUT...',
  '.TUUDDzzDDUUT...',
  '.TUUDDmmDDUUT...',
  '..TUUUDDDDUUUT..',
  '...TTUCCCCUTT...',
  '....TUCzzCUT....',
  '..PTUCDDCUTP....',
  '..QPTUUUUUTQ....',
  '....55...55.....',
  '....55...55.....',
  '...666...666....',
  '................',
];

const alchemistHit = alchemistIdleA.map(replaceToHit);
const alchemistDeath = simpleDeath(['FFFFF', 'GGGGG'], ['HHHHHH', 'GGGGGG'], 'F');

const necroIdleA = [
  '....EEE.........',
  '...EEFFEE.......',
  '..EEFFFFEE......',
  '.EEFFFFFFEE.....',
  '.EFF9999FFE.....',
  '.EF998e899FE....',
  'EFF98eeee89FE...',
  'EFF8ee00ee8FE...',
  'EFF8e0110e8FE...',
  '.EF98eeee89FE...',
  '.EFF999999FFE...',
  '...EFFFDDFFE....',
  '..EFFFFFFFFFE...',
  '.EEFFFF99FFFFE..',
  '.EFF99eeee99FE..',
  '.EFFEFFEEFFEFE..',
  '..EEFFFFFFFEE...',
  '...EF.....FE....',
  '...66..DD..66...',
  '..666..CC..666..',
  '..55........55..',
  '.666........666.',
];

const necroIdleB = [
  '................',
  '....EEE.........',
  '...EEFFEE.......',
  '..EEFFFFEE......',
  '.EEFFFFFFEE.....',
  '.EFF9999FFE.....',
  '.EF998e899FE....',
  'EFF98eeee89FE...',
  'EFF8ee00ee8FE...',
  'EFF8e0110e8FE...',
  '.EF98eeee89FE...',
  '.EFF999999FFE...',
  '...EFFFDDFFE....',
  '..EFFFFFFFFFE...',
  '.EEFFFF99FFFFE..',
  '.EFF99eeee99FE..',
  '.EFFEFFEEFFEFE..',
  '..EEFFFFFFFEE...',
  '...EF.....FE....',
  '..666..DD..666..',
  '..55...CC...55..',
  '.666........666.',
];

const necroHit = necroIdleA.map(replaceToHit);
const necroDeath = simpleDeath(['FFFFF', '99e99'], ['EFFFFF', 'FFDDFF'], 'E');

const berserkerIdleA = [
  '..RR..........RR..',
  '.RddR........RddR.',
  'RdcddR......RddcdR',
  'RdbccR..RR..RccbdR',
  '.RbccRRR44RRRccbR.',
  '..RbbR444444RbbR..',
  '...RR444C444RR....',
  '..RR444D4444RR....',
  '..R4444C4444R.....',
  '.R444BBSBB444R....',
  '.R44BBBSBBB44R....',
  '..RR44BDB44RR.....',
  '...R5666665R......',
  '..R665555566R.....',
  '.R46665556664R....',
  '.R444455554444R...',
  '..R44R5555R44R....',
  '..R4R..55..R4R....',
  '..R4R..66..R4R....',
  '..R5R......R5R....',
  '..R5R......R5R....',
  '...RR......RR.....',
];

const berserkerIdleB = [
  '..................',
  '..RR..........RR..',
  '.RddR........RddR.',
  'RdcddR......RddcdR',
  'RdbccR..RR..RccbdR',
  '.RbccRRR44RRRccbR.',
  '..RbbR444444RbbR..',
  '..RR444C444RR.....',
  '.RR444D4444RR.....',
  '.R4444C4444R......',
  'R444BBSBB444R.....',
  'R44BBBSBBB44R.....',
  '.RR44BDB44RR......',
  '..R5666665R.......',
  '.R665555566R......',
  'R46665556664R.....',
  'R444455554444R....',
  '.R44R5555R44R.....',
  '.R4R..55..R4R.....',
  '.R4R..66..R4R.....',
  '.R5R......R5R.....',
  '..RR......RR......',
];

const berserkerHit = berserkerIdleA.map(replaceToHit);
const berserkerDeath = simpleDeath(['44444', '4LL44'], ['hhhhhh', 'LLJJJJ'], 'a');

const clockmakerIdleA = [
  '.....99999......',
  '....9888889.....',
  '...98Q88Q889....',
  '...8QS88SQ88....',
  '....8dddd8......',
  '....d2222d......',
  '....ddPPdd......',
  '...888yy888.....',
  '..88y8888y88....',
  '.88y88yy88y88...',
  '.8888PQQP8888...',
  '..888PQQP888....',
  '...88yyyy88.P...',
  '...88N..N88.P...',
  '..P885..588QP...',
  '..Q55....55P....',
  '...55....55.....',
  '...66....66.....',
  '..666....666....',
  '..555....555....',
  '................',
  '................',
];

const clockmakerIdleB = [
  '................',
  '.....99999......',
  '....9888889.....',
  '...98Q88Q889....',
  '...8QS88SQ88....',
  '....8dddd8......',
  '....d2222d......',
  '....ddPPdd......',
  '...888yy888.....',
  '..88y8888y88....',
  '.88y88yy88y88...',
  '..888PQQP888.P..',
  '...88PQQP88.QP..',
  '...88yyyy88.P...',
  '..P88N..N88.....',
  '..Q885..588.....',
  '...55....55.....',
  '...66....66.....',
  '..666....666....',
  '..555....555....',
  '................',
  '................',
];

const clockmakerHit = clockmakerIdleA.map(replaceToHit);
const clockmakerDeath = simpleDeath(['99999', '88888'], ['88yyyy', 'PQQP88'], '8');

function replaceToHit(row: string): string {
  return row.replace(/[^.]/g, (ch) => {
    if (/[fghijJKL]/.test(ch)) return 'L';
    if (/[01R]/.test(ch)) return '1';
    return 'i';
  });
}

function simpleDeath(head: string[], body: string[], accent: string): string[] {
  const [hA = 'XXXXX', hB = 'XXXXX'] = head;
  const [bA = 'XXXXXX', bB = 'XXXXXX'] = body;
  return [
    '................',
    '................',
    '................',
    '................',
    `.....${accent}${hA}${accent}.....`,
    `.....${accent}${hB}${accent}.....`,
    `....${accent}${accent}${hA}${accent}${accent}....`,
    `....${accent}${accent}${hB}${accent}${accent}....`,
    '................',
    `...${accent}${accent}${bA}${accent}${accent}...`,
    `...${accent}${accent}${bB}${accent}${accent}...`,
    `...${accent}${accent}${bA}${accent}${accent}...`,
    '....5555555555..',
    '....6666666666..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ];
}

export function defineCharacterSprites(): void {
  const defs: { id: string; frames: string[][] }[] = [
    { id: 'char_soldier', frames: [soldierIdleA, soldierIdleB, soldierHit, soldierDeath] },
    { id: 'char_gambler', frames: [gamblerIdleA, gamblerIdleB, gamblerHit, gamblerDeath] },
    { id: 'char_alchemist', frames: [alchemistIdleA, alchemistIdleB, alchemistHit, alchemistDeath] },
    { id: 'char_necromancer', frames: [necroIdleA, necroIdleB, necroHit, necroDeath] },
    { id: 'char_berserker', frames: [berserkerIdleA, berserkerIdleB, berserkerHit, berserkerDeath] },
    { id: 'char_clockmaker', frames: [clockmakerIdleA, clockmakerIdleB, clockmakerHit, clockmakerDeath] },
  ];
  for (const d of defs) {
    defineSprite({
      id: d.id,
      frames: d.frames,
      anchor: 'bottom',
      anim: {
        idle: { name: 'idle', frames: [0, 1], frameDuration: 0.5, loop: true },
        hit: { name: 'hit', frames: [2], frameDuration: 0.15, loop: false },
        death: { name: 'death', frames: [3], frameDuration: 0.3, loop: false },
      },
    });
  }
}
