import { defineSprite } from './sprite';

const soldierIdleA = [
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
  '...5666...6665..',
];

const soldierIdleB = [
  '................',
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierHit = [
  '................',
  '.....LLLLLLL....',
  '....LiiiiiiiL...',
  '...LijjjjjjjiL..',
  '..LijjjjjjjjiL..',
  '..Lij11jjj11jiL.',
  '..LijjjjjjjjiL..',
  '..Lijjjj2jjjiL..',
  '..LiijjjjjjjiL..',
  '...LijjjjjjjiL..',
  '...LLLiiiiiLLL..',
  '..LLLLLLLLLLLL..',
  '.LLLLLLLLLLLLLL.',
  '.LLLLLLLLLLLLLL.',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '....LLL...LLL...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierDeath = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '......aaaaa.....',
  '....abbbbbba....',
  '...abcccccbba...',
  '..abcddc11cba...',
  '..abcddddcba....',
  '..abbcdddcba....',
  '...abbbbba......',
  '.aahhhhhhhhaa...',
  'ahhhxvhhhvxhhaa.',
  'ahhvxvvvvxvhha..',
  'aahhhhhhhhhhaa..',
  '..aaaaaaaaaaa...',
  '...5555555555...',
  '....555555555...',
  '....666666666...',
  '................',
  '................',
];

const gamblerIdleA = [
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerIdleB = [
  '................',
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerHit = gamblerIdleA.map(replaceToHit);
const gamblerDeath = [
  '................',
  '................',
  '................',
  '.....222222.....',
  '....22222222....',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcdddcba....',
  '....abcccba.....',
  '..4444444444....',
  '.44443aaaa3444..',
  '.444aaaaaaa444..',
  '..4444444444....',
  '...444aaa444....',
  '...44......44...',
  '...2........2...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

const alchemistIdleA = [
  '......FFFFF.....',
  '.....FGGGGGF....',
  '....FGGHHHGGF...',
  '....FGHHHHHGF...',
  '....FGH555HGF...',
  '....FGHbcbHGF...',
  '....FGHdDdHGF...',
  '....FGHcccHGF...',
  '....FGHHHHHGF...',
  '....FGGGGGGGF...',
  '...FGGHHHHHGGF..',
  '..FGGHCCCCCHGGF.',
  '..FGHCCzzzCCHGF.',
  '..FGHCzzmzzCHGF.',
  '..FGHCCzmzCCHGF.',
  '..FGHHCCCCCHHGF.',
  '..FGGGGGGGGGGGF.',
  '...FGGGGGGGGGF..',
  '....FF.....FF...',
  '....44.....44...',
  '...222.....222..',
  '...444.....444..',
];

const alchemistIdleB = [
  '................',
  '......FFFFF.....',
  '.....FGGGGGF....',
  '....FGGHHHGGF...',
  '....FGHHHHHGF...',
  '....FGH555HGF...',
  '....FGHbcbHGF...',
  '....FGHdDdHGF...',
  '....FGHcccHGF...',
  '....FGHHHHHGF...',
  '....FGGGGGGGF...',
  '...FGGHHHHHGGF..',
  '..FGGHCCDDCCHGGF',
  '..FGHCDDmmDCCHGF',
  '..FGHCCDmmCCCHGF',
  '..FGHHCCCCCHHGF.',
  '..FGGGGGGGGGGGF.',
  '...FGGGGGGGGGF..',
  '....FF.....FF...',
  '....44.....44...',
  '...222.....222..',
  '...444.....444..',
];

const alchemistHit = alchemistIdleA.map(replaceToHit);
const alchemistDeath = simpleDeath(['FFFFF', 'GGGGG'], ['HHHHHH', 'GGGGGG'], 'F');

const necroIdleA = [
  '...VVVVVVVV.....',
  '..VEEEEEEEEV....',
  '.VEEEdddddEEV...',
  '.VEedddddddeeV..',
  '.VedLLddLLdeeV..',
  '.VeddddddddeeV..',
  '.VedddddddddeV..',
  '.VeddddddddddV..',
  '.VVeddddddddeV..',
  '..VVdddddddeV...',
  '...VEEEEEEEV....',
  '..VEEwHHwHwEV...',
  '.VEEwHHHHwwHEV..',
  '.VEwwHHHwwwHEEV.',
  '.VEHwHwwHwHHEEV.',
  '..VEEwwHHHwEEV..',
  '..VVEEEEEEEEVV..',
  '...VEE.....EEV..',
  '...VV.......VV..',
  '...VE.......EV..',
  '...VE.......EV..',
  '...VV.......VV..',
];

const necroIdleB = [
  '................',
  '...VVVVVVVV.....',
  '..VEEEEEEEEV....',
  '.VEEEdddddEEV...',
  '.VEedddddddeeV..',
  '.VedLLddLLdeeV..',
  '.VeddddddddeeV..',
  '.VedddddddddeV..',
  '.VeddddddddddV..',
  '.VVeddddddddeV..',
  '..VVdddddddeV...',
  '...VEEEEEEEV....',
  '..VEEHwHHwHHEV..',
  '.VEEHwHHHwwHHEV.',
  '.VEwwHHHwwwHEEV.',
  '.VEEwwHwwHwwHEV.',
  '..VVEEEEEEEEVV..',
  '...VEE.....EEV..',
  '...VV.......VV..',
  '...VE.......EV..',
  '...VV.......VV..',
  '................',
];

const necroHit = necroIdleA.map(replaceToHit);
const necroDeath = simpleDeath(['VVVVV', 'EEEEE'], ['HHHwww', 'wwwHHH'], 'V');

const berserkerIdleA = [
  '....sssssssss...',
  '...stsssssssts..',
  '..sstsssssssts..',
  '..stttsssssttt..',
  '..sstsvvvvsstss.',
  '...assdddssa....',
  '...adddhdddda...',
  '...ad11d11da....',
  '...addhdhdda....',
  '...adddhhdda....',
  '...adddddda.....',
  '..6aaaccaaa6....',
  '.669hhvvhh966...',
  '669hhhvvhhh966..',
  '.66hhhhhhhh66...',
  '.66hhJLLJhh66...',
  '.66hhJJJJhh66...',
  '..66hhhhhh66....',
  '..5555..5555....',
  '..6666..6666....',
  '..6666..6666....',
  '..5555..5555....',
];

const berserkerIdleB = [
  '................',
  '....sssssssss...',
  '...stsssssssts..',
  '..sstsssssssts..',
  '..stttsssssttt..',
  '...sstvvvvsst...',
  '...assdddssa....',
  '...adddhdddda...',
  '...ad11d11da....',
  '...addhdhdda....',
  '...adddhhdda....',
  '..6aaaccaaa6....',
  '.669hhvvhh966...',
  '669hhhvvhhh966..',
  '.66hhhhhhhh66...',
  '.66hhJLLJhh66...',
  '.66hhJJJJhh66...',
  '..66hhhhhh66....',
  '..5555..5555....',
  '..6666..6666....',
  '..5555..5555....',
  '................',
];

const berserkerHit = berserkerIdleA.map(replaceToHit);
const berserkerDeath = simpleDeath(['sssss', 'stttt'], ['hhhhhh', 'LLJJJJ'], 's');

const clockmakerIdleA = [
  '.....yyyyyy.....',
  '....yyyNNyyy....',
  '...yyNNNNNNyy...',
  '...yNNyxxyNNy...',
  '..yNNxxvvxxNNy..',
  '..yNxvvccvxvNy..',
  '..yNNNNxxNNNNy..',
  '..yNNNvvvvNNNy..',
  '..yNNxc22cxNNy..',
  '..yNNNvvvvNNNy..',
  '...yyyNNNNyyy...',
  '...yyxvvvvxyy...',
  '..8888yyyy8888..',
  '.888xvv88vvx888.',
  '.888vx8vvx8vx88.',
  '.888vvv88vvvx88.',
  '..888vvvvvv888..',
  '...88NN..NN88...',
  '...88.....88....',
  '...55.....55....',
  '...55.....55....',
  '...66.....66....',
];

const clockmakerIdleB = [
  '................',
  '.....yyyyyy.....',
  '....yyyNNyyy....',
  '...yyNNNNNNyy...',
  '...yNNyxxyNNy...',
  '..yNNxvvvvxNNy..',
  '..yNxvvccvxvNy..',
  '..yNNNNxxNNNNy..',
  '..yNNNvvvvNNNy..',
  '..yNNxc22cxNNy..',
  '..yNNNvvvvNNNy..',
  '...yyyNNNNyyy...',
  '..8888yyyy8888..',
  '.888vxvvvvvx888.',
  '.888vx8vvx8vx88.',
  '.888vvvvvvvvx88.',
  '..888vvvvvv888..',
  '...88NN..NN88...',
  '...88.....88....',
  '...55.....55....',
  '...66.....66....',
  '................',
];

const clockmakerHit = clockmakerIdleA.map(replaceToHit);
const clockmakerDeath = simpleDeath(['yyyyy', 'NNNNN'], ['vvvvvv', '888888'], 'y');

function replaceToHit(row: string): string {
  return row.replace(/[hijfg]/g, 'L').replace(/[abcde]/g, 'i');
}

function simpleDeath(head: string[], body: string[], accent: string): string[] {
  const [hA = 'XXXXX', hB = 'XXXXX'] = head;
  const [bA = 'XXXXXX', bB = 'XXXXXX'] = body;
  return [
    '................',
    '................',
    '................',
    '................',
    `.....${accent}${hA}${accent}.....`,
    `.....${accent}${hB}${accent}.....`,
    `....${accent}${accent}${hA}${accent}${accent}....`,
    `....${accent}${accent}${hB}${accent}${accent}....`,
    '................',
    `...${accent}${accent}${bA}${accent}${accent}...`,
    `...${accent}${accent}${bB}${accent}${accent}...`,
    `...${accent}${accent}${bA}${accent}${accent}...`,
    '....5555555555..',
    '....6666666666..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ];
}

export function defineCharacterSprites(): void {
  const defs: { id: string; frames: string[][] }[] = [
    { id: 'char_soldier', frames: [soldierIdleA, soldierIdleB, soldierHit, soldierDeath] },
    { id: 'char_gambler', frames: [gamblerIdleA, gamblerIdleB, gamblerHit, gamblerDeath] },
    { id: 'char_alchemist', frames: [alchemistIdleA, alchemistIdleB, alchemistHit, alchemistDeath] },
    { id: 'char_necromancer', frames: [necroIdleA, necroIdleB, necroHit, necroDeath] },
    { id: 'char_berserker', frames: [berserkerIdleA, berserkerIdleB, berserkerHit, berserkerDeath] },
    { id: 'char_clockmaker', frames: [clockmakerIdleA, clockmakerIdleB, clockmakerHit, clockmakerDeath] },
  ];
  for (const d of defs) {
    defineSprite({
      id: d.id,
      frames: d.frames,
      anchor: 'bottom',
      anim: {
        idle: { name: 'idle', frames: [0, 1], frameDuration: 0.5, loop: true },
        hit: { name: 'hit', frames: [2], frameDuration: 0.15, loop: false },
        death: { name: 'death', frames: [3], frameDuration: 0.3, loop: false },
      },
    });
  }
}
