import { defineSprite } from './sprite';

const soldierIdleA = [
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
  '...5666...6665..',
];

const soldierIdleB = [
  '................',
  '.....aaaaaaa....',
  '....abbbbbbba...',
  '...abcccccccba..',
  '..abcdddcdddcba.',
  '..abc11cdc11cba.',
  '..abcdddddddcba.',
  '..abcddd2dddcba.',
  '..abccddddddcba.',
  '...abcccccccba..',
  '...aaaPPPPPaaa..',
  '..ahghhhhhhhgha.',
  '.ahhxvhhhhhvxhha',
  '.ahhvxvvvvvxvhha',
  '..ahhhhxxxhhhha.',
  '..ahhhhhhhhhhha.',
  '..aahhhhhhhhhaa.',
  '....aaa...aaa...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierHit = [
  '................',
  '.....LLLLLLL....',
  '....LiiiiiiiL...',
  '...LijjjjjjjiL..',
  '..LijjjjjjjjiL..',
  '..Lij11jjj11jiL.',
  '..LijjjjjjjjiL..',
  '..Lijjjj2jjjiL..',
  '..LiijjjjjjjiL..',
  '...LijjjjjjjiL..',
  '...LLLiiiiiLLL..',
  '..LLLLLLLLLLLL..',
  '.LLLLLLLLLLLLLL.',
  '.LLLLLLLLLLLLLL.',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '..LLLLLLLLLLLL..',
  '....LLL...LLL...',
  '....555...555...',
  '....555...555...',
  '....556...655...',
  '...6666...6666..',
];

const soldierDeath = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '......aaaaa.....',
  '....abbbbbba....',
  '...abcccccbba...',
  '..abcddc11cba...',
  '..abcddddcba....',
  '..abbcdddcba....',
  '...abbbbba......',
  '.aahhhhhhhhaa...',
  'ahhhxvhhhvxhhaa.',
  'ahhvxvvvvxvhha..',
  'aahhhhhhhhhhaa..',
  '..aaaaaaaaaaa...',
  '...5555555555...',
  '....555555555...',
  '....666666666...',
  '................',
  '................',
];

const gamblerIdleA = [
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerIdleB = [
  '................',
  '....22222222....',
  '....22222222....',
  '....22222222....',
  '...0222222220...',
  '.xxxx22222xxxx..',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcccccba....',
  '...abcd2dcba....',
  '...abcdddcba....',
  '...abccccccba...',
  '..4444444444....',
  '.44443axxa3444..',
  '.44443aaaa3444..',
  '.44443aaaa3444..',
  '..444aaaaa444...',
  '...ab.....ab....',
  '...a......a.....',
  '...4.......4....',
  '..222.....222...',
  '..444.....444...',
];

const gamblerHit = gamblerIdleA.map(replaceToHit);
const gamblerDeath = [
  '................',
  '................',
  '................',
  '.....222222.....',
  '....22222222....',
  '...abcccccba....',
  '...abc1c1cba....',
  '...abcdddcba....',
  '....abcccba.....',
  '..4444444444....',
  '.44443aaaa3444..',
  '.444aaaaaaa444..',
  '..4444444444....',
  '...444aaa444....',
  '...44......44...',
  '...2........2...',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
];

const alchemistIdleA = [
  '......FFFF......',
  '.....FGGGGF.....',
  '....FGHHHHGF....',
  '...FGHFFFFHGF...',
  '...FHFzzFFHGF...',
  '...FHFRRRRHGF...',
  '...FGHFRFHGGF...',
  '....FGHHHGGF....',
  '...TTTUUUTTT....',
  '..TUUUDDDUUUT...',
  '.TUUDDzzDDUUT...',
  '.TUUDDmmDDUUT...',
  '.TUUUDDDDUUUT...',
  '..TTUCCCCUTT....',
  '...TUCzzCUT.....',
  '...TUCDDCUT.....',
  '..PTUUUUUUTP....',
  '..QP.....PQ.....',
  '....55...55.....',
  '....55...55.....',
  '...666...666....',
  '...555...555....',
];

const alchemistIdleB = [
  '................',
  '......FFFF......',
  '.....FGGGGF.....',
  '....FGHHHHGF....',
  '...FGHFFFFHGF...',
  '...FHFzzFFHGF...',
  '...FHFRRRRHGF...',
  '...FGHFRFHGGF...',
  '....FGHHHGGF....',
  '...TTTUUUTTT....',
  '..TUUUDDDUUUT...',
  '.TUUDDzzDDUUT...',
  '.TUUDDmmDDUUT...',
  '..TUUUDDDDUUUT..',
  '...TTUCCCCUTT...',
  '....TUCzzCUT....',
  '..PTUCDDCUTP....',
  '..QPTUUUUUTQ....',
  '....55...55.....',
  '....55...55.....',
  '...666...666....',
  '................',
];

const alchemistHit = alchemistIdleA.map(replaceToHit);
const alchemistDeath = simpleDeath(['FFFFF', 'GGGGG'], ['HHHHHH', 'GGGGGG'], 'F');

const necroIdleA = [
  '......9.9.......',
  '.....99999......',
  '....98e8e89.....',
  '....8eeee8......',
  '...6ee00ee6.....',
  '...6e0110e6.....',
  '...6ee11ee6.....',
  '....6e1116......',
  '....66eee6......',
  '....VFFFFV......',
  '...VEFFFFEV.....',
  '..VEEFFFFEEV....',
  '.VEEFF99FFEEV...',
  '.VEFF9ee9FFEV...',
  '.VEFFEFFEFFEVP..',
  '..VEFFFFFEEVPQ..',
  '..VVEEEEEFFVP...',
  '...VEE...EEV....',
  '...66.....66....',
  '..666.....666...',
  '..55.......55...',
  '.666.......666..',
];

const necroIdleB = [
  '................',
  '......9.9.......',
  '.....99999......',
  '....98e8e89.....',
  '....8eeee8......',
  '...6ee00ee6.....',
  '...6e0110e6.....',
  '...6ee11ee6.....',
  '....6e1116......',
  '....66eee6......',
  '....VFFFFV......',
  '..VEEFFFFEEV....',
  '.VEEEFFFFEEEV...',
  '.VEEFF99FFEEV...',
  '.VEFF9ee9FFEVP..',
  '.VEFFEFFEFFEVPQ.',
  '..VEFFFFFEEVPQ..',
  '..VVEEEEEFFVP...',
  '...VEE...EEV....',
  '..666.....666...',
  '..55.......55...',
  '.555.......555..',
  '.666.......666..',
];

const necroHit = necroIdleA.map(replaceToHit);
const necroDeath = simpleDeath(['99999', '8ed8e'], ['EEEFFF', 'FFVEEE'], '6');

const berserkerIdleA = [
  'QQ..........QQ..',
  'PQQ........QQP..',
  '.PQQ..444..QQP.',
  '..PQQ444444QQ..',
  '...a444444a....',
  '...a400004a....',
  '...a4dddd4a....',
  '....a6666a.....',
  '..66hhhhhh66Q..',
  '.669hhhhhh69QP.',
  '669hJJLLJJh96P.',
  '.66hJLLLLJh66P.',
  '..66hJJJJh66.6.',
  '...66hhhh66..6.',
  '..555555555..6.',
  '..666566566..6.',
  '.6666..6666..6.',
  '.5555..5555..6.',
  '.6666..6666.QP.',
  '.5555..5555QP..',
  '................',
  '................',
];

const berserkerIdleB = [
  '................',
  'QQ..........QQ..',
  'PQQ........QQP..',
  '.PQQ..444..QQP.',
  '..PQQ444444QQ..',
  '...a444444a....',
  '...a400004a....',
  '...a4dddd4a....',
  '....a6666a.....',
  '.669hhhhhh69Q...',
  '669hJJLLJJh96P..',
  '.66hJLLLLJh66P..',
  '..66hJJJJh66P...',
  '...66hhhh66.6...',
  '..555555555.6...',
  '..666566566.6...',
  '.6666..6666.6...',
  '.5555..5555QP...',
  '.6666..6666P....',
  '.5555..5555.....',
  '................',
  '................',
];

const berserkerHit = berserkerIdleA.map(replaceToHit);
const berserkerDeath = simpleDeath(['44444', '4LL44'], ['hhhhhh', 'LLJJJJ'], 'a');

const clockmakerIdleA = [
  '.....99999......',
  '....9888889.....',
  '...98Q88Q889....',
  '...8QS88SQ88....',
  '....8dddd8......',
  '....d2222d......',
  '....ddPPdd......',
  '...888yy888.....',
  '..88y8888y88....',
  '.88y88yy88y88...',
  '.8888PQQP8888...',
  '..888PQQP888....',
  '...88yyyy88.P...',
  '...88N..N88.P...',
  '..P885..588QP...',
  '..Q55....55P....',
  '...55....55.....',
  '...66....66.....',
  '..666....666....',
  '..555....555....',
  '................',
  '................',
];

const clockmakerIdleB = [
  '................',
  '.....99999......',
  '....9888889.....',
  '...98Q88Q889....',
  '...8QS88SQ88....',
  '....8dddd8......',
  '....d2222d......',
  '....ddPPdd......',
  '...888yy888.....',
  '..88y8888y88....',
  '.88y88yy88y88...',
  '..888PQQP888.P..',
  '...88PQQP88.QP..',
  '...88yyyy88.P...',
  '..P88N..N88.....',
  '..Q885..588.....',
  '...55....55.....',
  '...66....66.....',
  '..666....666....',
  '..555....555....',
  '................',
  '................',
];

const clockmakerHit = clockmakerIdleA.map(replaceToHit);
const clockmakerDeath = simpleDeath(['99999', '88888'], ['88yyyy', 'PQQP88'], '8');

function replaceToHit(row: string): string {
  return row.replace(/[^.]/g, (ch) => {
    if (/[fghijJKL]/.test(ch)) return 'L';
    if (/[01R]/.test(ch)) return '1';
    return 'i';
  });
}

function simpleDeath(head: string[], body: string[], accent: string): string[] {
  const [hA = 'XXXXX', hB = 'XXXXX'] = head;
  const [bA = 'XXXXXX', bB = 'XXXXXX'] = body;
  return [
    '................',
    '................',
    '................',
    '................',
    `.....${accent}${hA}${accent}.....`,
    `.....${accent}${hB}${accent}.....`,
    `....${accent}${accent}${hA}${accent}${accent}....`,
    `....${accent}${accent}${hB}${accent}${accent}....`,
    '................',
    `...${accent}${accent}${bA}${accent}${accent}...`,
    `...${accent}${accent}${bB}${accent}${accent}...`,
    `...${accent}${accent}${bA}${accent}${accent}...`,
    '....5555555555..',
    '....6666666666..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ];
}

export function defineCharacterSprites(): void {
  const defs: { id: string; frames: string[][] }[] = [
    { id: 'char_soldier', frames: [soldierIdleA, soldierIdleB, soldierHit, soldierDeath] },
    { id: 'char_gambler', frames: [gamblerIdleA, gamblerIdleB, gamblerHit, gamblerDeath] },
    { id: 'char_alchemist', frames: [alchemistIdleA, alchemistIdleB, alchemistHit, alchemistDeath] },
    { id: 'char_necromancer', frames: [necroIdleA, necroIdleB, necroHit, necroDeath] },
    { id: 'char_berserker', frames: [berserkerIdleA, berserkerIdleB, berserkerHit, berserkerDeath] },
    { id: 'char_clockmaker', frames: [clockmakerIdleA, clockmakerIdleB, clockmakerHit, clockmakerDeath] },
  ];
  for (const d of defs) {
    defineSprite({
      id: d.id,
      frames: d.frames,
      anchor: 'bottom',
      anim: {
        idle: { name: 'idle', frames: [0, 1], frameDuration: 0.5, loop: true },
        hit: { name: 'hit', frames: [2], frameDuration: 0.15, loop: false },
        death: { name: 'death', frames: [3], frameDuration: 0.3, loop: false },
      },
    });
  }
}
